shell:
  script:
    - cd /home/maw1/hv_3/Backend/foodbuddy_mongo
    - pwd
    - gradle clean build
    - cd build/libs/
    - sudo yes | sudo cp foodbuddy-0.0.2-boot.jar /home/maw1/docker/foodbuddy/
    - cd /home/maw1/docker/foodbuddy
    - sudo docker stop foodbuddy
    - sudo docker container prune
    - sudo docker build -t maximillion1112/foodbuddy:latest
    - sudo docker run -d -p 8080:8080 --name foodbuddy maximillion1112/foodbuddy:latest
    - sleep 10
    - sudo docker logs foodbuddy > /home/maw1/docker/logs/log.txt
