shell:
  script:
    - cd /home/maw1/hv_3/Backend/foodbuddy_mongo
    - sudo ./gradlew clean build
    - cd build/libs/
    - sudo mv -f foodbuddy-0.0.2-boot.jar /home/maw1/docker/foodbuddy/
    - cd /home/maw1/docker/foodbuddy
    - sudo docker stop foodbuddy
    - sudo docker container prune -f
    - sudo docker build -t maximillion1112/foodbuddy:latest .
    - sudo docker run -d -p 8080:8080 --name foodbuddy maximillion1112/foodbuddy:latest
    - sleep 7
    - sudo docker logs foodbuddy | sudo tee /home/maw1/docker/logs/log.txt

#Questions:
#I need to update the repository that is stored on the server
#   How do I do that in one line in the gitlab-runner shell

#I need to run gradle clean build but gradle is only installed for root user
#   How do I install gradle everywhere and/or fix this problem
#gradle is being super weird. I can run it without using sudo on my user account
#but if I run sudo gradle clean build the command is not found

#when I run gradle clean build without sudo on my account it doesn't
#work because I don't have full root permissions

#if I first run sudo bash to be root user then I can run gradle clean build
#everything works as intended. But I cant get into sudo bash in gitlab-runner