shell:
  script:
    - cd /home/maw1/builds/c6ptsrCn/0/cs309/spring-2020/hv_3/Backend/foodbuddy_mongo
    - sudo chmod +x gradlew
    - sudo dos2unix gradlew
    - sudo ./gradlew clean build
    - cd build/libs/
    - sudo mv -f foodbuddy-0.0.2-boot.jar /home/maw1/docker/foodbuddy/
    - cd /home/maw1/docker/foodbuddy
    - sudo docker stop foodbuddy
    - sudo docker container prune -f
    - sudo docker build -t maximillion1112/foodbuddy:latest .
    - sudo docker run -d -p 8080:8080 --name foodbuddy maximillion1112/foodbuddy:latest
    - sleep 10
    - sudo docker logs foodbuddy | sudo tee /home/maw1/docker/logs/food_log.txt
